"""empty message

Revision ID: 4c7bb9700bdb
Revises: ed657e16ce20
Create Date: 2018-07-07 07:35:47.683932

"""

# revision identifiers, used by Alembic.
revision = '4c7bb9700bdb'
down_revision = 'ed657e16ce20'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
