"""empty message

Revision ID: d5b1dcd8ab6f
Revises: 4c7bb9700bdb
Create Date: 2018-07-08 13:45:51.342728

"""

# revision identifiers, used by Alembic.
revision = 'd5b1dcd8ab6f'
down_revision = '4c7bb9700bdb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address',
    sa.Column('address_id', sa.Integer(), nullable=False),
    sa.Column('street_address', sa.String(length=255), nullable=True),
    sa.Column('postal_code', sa.Integer(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('address_id')
    )
    op.create_table('category',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('category_name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('category_id')
    )
    op.create_table('job',
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('job_title', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_table('stage',
    sa.Column('stage_id', sa.Integer(), nullable=False),
    sa.Column('stage_title', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('stage_id')
    )
    op.create_table('office',
    sa.Column('office_id', sa.Integer(), nullable=False),
    sa.Column('address_id', sa.Integer(), nullable=False),
    sa.Column('office_name', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['address_id'], ['address.address_id'], ),
    sa.PrimaryKeyConstraint('office_id')
    )
    op.create_table('product',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=True),
    sa.Column('product_description', sa.Text(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('pre_approved', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.category_id'], ),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_table('request',
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('request_justfication', sa.Text(), nullable=True),
    sa.Column('request_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.product_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('request_id')
    )
    op.add_column(u'user', sa.Column('first_name', sa.String(length=255), nullable=True))
    op.add_column(u'user', sa.Column('last_name', sa.String(length=255), nullable=True))
    op.add_column(u'user', sa.Column('phone_number', sa.String(length=50), nullable=True))
    op.add_column(u'user', sa.Column('user_id', sa.Integer(), nullable=False))
    op.alter_column(u'user', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column(u'user', 'password',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column(u'user', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'user', sa.Column('id', sa.INTEGER(), nullable=False))
    op.alter_column(u'user', 'password',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column(u'user', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_column(u'user', 'user_id')
    op.drop_column(u'user', 'phone_number')
    op.drop_column(u'user', 'last_name')
    op.drop_column(u'user', 'first_name')
    op.drop_table('request')
    op.drop_table('product')
    op.drop_table('office')
    op.drop_table('stage')
    op.drop_table('job')
    op.drop_table('category')
    op.drop_table('address')
    # ### end Alembic commands ###
